// A 4-day exam plan generated by FocusPlan itself with DeepSeek (deepseek-flash):
// 841 input + 6,783 output tokens, one call, ~31 s, about $0.004–0.008.
const S = (short, blockNums, tasks) => ({ short, blockNums, tasks });

export const MICRO_EXAMPLE = {
  id: "example-micro",
  emoji: "📘",
  name: "Microeconomics Exam Sprint (example)",
  label: "Microeconomics exam",
  summary: "4 intense days · 7 topics, mock exam, exam day",
  color: "#ffb454",
  template: { wake: "08:00", sleep: "22:00", blockMin: 50, breakMin: 10 },
  goal: `Pass my Microeconomics exam on the last day of this plan.
Topics: (1) consumer theory — preferences, utility, indifference curves, budget constraint, utility maximization;
(2) demand — income and substitution effects, Slutsky equation, elasticities, consumer surplus;
(3) producer theory — production functions, returns to scale, cost minimization, short- vs long-run cost curves;
(4) perfect competition — firm and industry supply, long-run equilibrium, welfare and deadweight loss;
(5) monopoly and price discrimination (1st, 2nd, 3rd degree);
(6) game theory and oligopoly — Nash equilibrium, Cournot, Bertrand, Stackelberg;
(7) market failures — externalities, Pigouvian taxes, public goods; general equilibrium and Pareto efficiency.
The exam mixes calculation problems (optimization with derivatives, Lagrangian) and short explanations with graphs.
I'm weakest at game theory/oligopoly and at the Slutsky decomposition.`,
  usage: { input: 841, output: 6783, calls: 1, seconds: 30.8, cost: { low: 0.0042, high: 0.0084 } },
  days: [
    { label: "Consumer, demand, producer foundations", blocks: [
      S("Consumer theory core", [1, 2, 3], ["Write 1-page preference axioms and utility definitions", "Derive MRS = MUx/MUy = Px/Py tangency", "Solve 4 Cobb-Douglas utility maximization problems"]),
      S("Slutsky decomposition deep", [4, 5, 6], ["Derive Slutsky equation from expenditure function", "Compute income and substitution effects for 3 price changes", "Graph 2 Slutsky decompositions with indifference curves"]),
      S("Producer theory", [7, 8, 9], ["Summarize returns to scale with 3 production functions", "Solve 4 cost-minimization Lagrangian problems", "Sketch short-run vs long-run cost curves for 2 technologies"]),
      S("Mixed recall practice", [10, 11], ["Redo 3 utility max and 3 cost min without notes", "Write 6 formula flashcards from today"]),
    ]},
    { label: "Competition, monopoly, oligopoly, failures", blocks: [
      S("Perfect competition", [1, 2], ["Derive firm supply as MC above AVC", "Solve 3 long-run equilibrium problems", "Graph deadweight loss from a tax"]),
      S("Monopoly & price discrimination", [3, 4, 5], ["Solve 3 monopoly MR = MC pricing problems", "Compare 1st, 2nd, 3rd degree discrimination with examples", "Graph monopoly DWL and consumer surplus"]),
      S("Game theory & oligopoly deep", [6, 7, 8, 9], ["Find Nash equilibrium in 2 payoff matrices", "Solve Cournot for 2 and 3 firms", "Derive Stackelberg leader-follower quantities", "Compare Bertrand and Cournot outcomes in 1 table"]),
      S("Market failures and recall", [10, 11], ["Solve 1 Pigouvian tax and 1 public good problem", "Graph externality deadweight loss and Pigouvian tax", "State Pareto efficiency and 2 welfare theorems", "Recall Slutsky equation from memory and correct notes"]),
    ]},
    { label: "Mixed review and timed practice", blocks: [
      S("Consumer & demand review", [1, 2], ["Recite utility maximization steps from memory", "Redo 2 Slutsky decomposition mistakes from Day 1", "Solve 3 elasticity and consumer surplus problems"]),
      S("Producer & competition review", [3, 4], ["Redraw short-run and long-run cost curves", "Solve 2 cost minimization and 2 long-run equilibrium problems", "Explain returns to scale in 3 sentences"]),
      S("Monopoly & market failures review", [5, 6], ["Solve 2 price discrimination and 2 externality problems", "Sketch monopoly DWL and Pigouvian tax graphs", "Write 3 public good and Pareto efficiency conditions"]),
      S("Timed mixed exam run", [7, 8, 9], ["Do 50-min timed calculation set, no notes", "Do 50-min timed graph and short-answer set", "Mark mistakes and list exact error causes"]),
      S("Weak spot repair", [10, 11], ["Redo 3 Cournot, Bertrand, Stackelberg problems", "Redo 3 Slutsky decompositions with fresh numbers", "Write 5-step fix list for each weak topic"]),
    ]},
    { label: "Exam-day confidence and performance", blocks: [
      S("Morning summary confidence", [1, 2, 3, 4], ["Read consumer and demand summary sheets aloud", "Read producer and competition summary sheets aloud", "Read monopoly and game theory summary sheets aloud", "Read market failures and general equilibrium summary sheets aloud"]),
      S("Formula and graph recall", [5, 6], ["Write 10 key formulas from memory", "Sketch 4 core graphs with labels", "Recite Slutsky and Cournot steps once"]),
      S("Light mental prep", [7, 8], ["Pack calculator, ID, water, and spare pen", "Plan to answer calculation problems first", "Do 5 slow breaths before entering exam"]),
      S("Exam performance", [9, 10, 11], ["Read each question twice and note givens", "Show optimization steps and label graphs", "Check units, signs, and final answers"]),
    ]},
  ],
};
