// A relaxed 3-day study plan generated by FocusPlan itself with DeepSeek (deepseek-flash):
// 691 input + 2,970 output tokens, one call, ~13 s, about $0.002–0.004.
const S = (short, blockNums, tasks) => ({ short, blockNums, tasks });

export const STUDY_EXAMPLE = {
  id: "example-study",
  emoji: "📗",
  name: "Balanced Study Week (example)",
  label: "Normal study week",
  summary: "3 relaxed days · Statistics, Marketing, an essay",
  color: "#35d07f",
  template: { wake: "09:00", sleep: "21:00", blockMin: 45, breakMin: 15 },
  goal: `A normal, balanced study week for my university courses — steady progress, not cramming.
Statistics: practice problems on probability and the normal distribution.
Marketing: read 2 textbook chapters and make short notes.
English: write and edit a 1,000-word essay due at the end of the plan.
Keep one short daily review so things stick.`,
  usage: { input: 691, output: 2970, calls: 1, seconds: 13.2, cost: { low: 0.0019, high: 0.0038 } },
  days: [
    { label: "Probability, marketing ch.1, essay start", blocks: [
      S("Stats: probability rules", [1, 2], ["Read probability chapter, about 12 pages", "Copy 6 key rules onto summary sheet", "Work through 3 solved examples step by step"]),
      S("Probability problem practice", [3, 4], ["Solve 8 probability problems", "Rate each answer confidence 1-3", "Redo the 3 hardest without notes"]),
      S("Essay outline and thesis", [5], ["Write 1-sentence thesis statement", "Outline 4 body paragraphs on one page", "List 5 sources to cite"]),
      S("Marketing chapter 1", [6, 7], ["Read textbook chapter 1 fully", "Write 1-page notes with 8 key terms", "Add 3 real brand examples"]),
      S("Essay intro and paragraph 1", [8], ["Draft 150-word introduction", "Draft first 200-word body paragraph", "Mark 2 claims needing evidence"]),
      S("Daily recall review", [9], ["Write 5 key points from memory", "Check notes and fix gaps", "Note 1 weak topic for tomorrow"]),
    ]},
    { label: "Normal distribution, ch.2, essay drafting", blocks: [
      S("Stats: normal distribution", [1, 2], ["Read the normal distribution section", "Write z-score formula and table steps", "Work 3 solved z-score examples"]),
      S("Normal distribution problems", [3, 4], ["Solve 8 z-score and probability problems", "Sketch the curve for each answer", "Redo 2 wrong problems from memory"]),
      S("Marketing chapter 2", [5, 6], ["Read textbook chapter 2 fully", "Write 1-page notes with 8 key terms", "Compare to chapter 1 notes in 3 lines"]),
      S("Essay body paragraphs", [7], ["Draft body paragraphs 2 and 3", "Add 3 citations with page numbers", "Bring draft to 700 words total"]),
      S("Mixed stats practice", [8], ["Solve 5 mixed probability and normal problems", "Time the set at 30 minutes", "List every mistake and its cause"]),
      S("Spaced review of day 1", [9], ["Redo yesterday's 3 marked mistakes", "Recite 6 probability rules without notes", "Write 3 marketing terms from memory"]),
    ]},
    { label: "Essay finish, timed run, light review", blocks: [
      S("Stats summary confidence review", [1, 2], ["Read the full stats summary sheet aloud", "Recite probability and z-score steps", "Flag 2 formulas still shaky"]),
      S("Marketing notes condense", [3], ["Condense chapters 1-2 notes to one page", "Say 10 key terms and meanings aloud"]),
      S("Essay final edit", [4, 5], ["Edit for clarity and flow, full read", "Check word count hits 1,000 plus or minus 50", "Format citations and reference list"]),
      S("Essay proofread and submit", [6], ["Proofread final draft once slowly", "Submit essay before the deadline", "Save a backup copy"]),
      S("Weak spot fixing", [7], ["Redo 3 flagged stats problems without notes", "Write a one-line rule for each fix"]),
      S("Timed run and week wrap-up", [8, 9], ["Solve 5 stats problems in 25 minutes", "Self-quiz 10 marketing terms", "List 3 topics for next week"]),
    ]},
  ],
};
